[package]
name = "message-format"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
icu = "1.5.0"
icu_decimal = "1.5.0"
once_cell = "1.19.0"
ordered-float = "4.2.0"
regex = "1.10.4"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
